// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { shopifyBlock } from "./index";

export const shopifyBlockSchema = parseBlockSchema(shopifyBlock);
export const shopifyCredentialsSchema = parseBlockCredentials(
  shopifyBlock.id,
  auth,
);
